/*
 * Quelora — quelora-widget-community
 * Copyright (C) 2026 Germán Zelaya — https://quelora.org
 * SPDX-License-Identifier: AGPL-3.0-only
 *
 * This file is part of Quelora. See the LICENSE file for terms.
 */

/* filepath: quelora/modules/features/mention.js */
import UtilsModule from "../../core/utils.js"; 
import GuardModule from '../../core/guard.js';

/**
 * Manages mention functionality.
 * Input: Handles @username autocomplete in textareas and contenteditable divs.
 * Output: Global listener for clicks on "mention:*" elements generated by Wasm.
 */
class MentionModule {
    // ============================================================
    // 1. INSTANCE METHODS (Para escribir menciones en inputs)
    // ============================================================
    
    constructor(inputElement, searchMentionsFn, config = {}) {
        this.inputElement = inputElement;
        this.searchMentionsFn = searchMentionsFn;
        this.debounceTime = config.debounceTime || 600;
        this.debouncedHandleMention = null;
        this.initializeMention();
    }

    initializeMention() {
        this.debouncedHandleMention = UtilsModule.debounce(
            this.handleMentionSearch.bind(this),
            this.debounceTime
        );
        this.inputElement.addEventListener('input', this.handleInput.bind(this));
    }

    /**
     * Obtiene el valor y la posición del cursor de forma agnóstica
     * (funciona para input/textarea y div contenteditable).
     */
    getInputState(target) {
        if (target.isContentEditable) {
            const value = target.textContent;
            let cursorPosition = 0;
            
            const selection = window.getSelection();
            if (selection.rangeCount > 0) {
                const range = selection.getRangeAt(0);
                const preCaretRange = range.cloneRange();
                preCaretRange.selectNodeContents(target);
                preCaretRange.setEnd(range.endContainer, range.endOffset);
                cursorPosition = preCaretRange.toString().length;
            }
            return { value, cursorPosition };
        } else {
            return { 
                value: target.value, 
                cursorPosition: target.selectionStart 
            };
        }
    }

    handleInput(event) {
        const { value, cursorPosition } = this.getInputState(event.target);
        
        if (!value) return;

        const textBeforeCursor = value.slice(0, cursorPosition);
        // Regex: Busca @palabra al final del texto antes del cursor
        const mentionMatch = textBeforeCursor.match(/@(\w+)$/);

        if (mentionMatch && !/\s/.test(mentionMatch[1])) {
            this.debouncedHandleMention(mentionMatch[1]);
        }
    }

    handleMentionSearch(username) {
        this.searchMentionsFn(this.inputElement, username);
    }

    replaceMention(selectedMention) {
        const { value, cursorPosition } = this.getInputState(this.inputElement);
        const textBeforeCursor = value.slice(0, cursorPosition);
        const mentionMatch = textBeforeCursor.match(/@(\w+)$/);

        if (mentionMatch) {
            const startIndex = textBeforeCursor.lastIndexOf(mentionMatch[0]);
            const newText = value.slice(0, startIndex) + `@${selectedMention} ` + value.slice(cursorPosition);
            
            if (this.inputElement.isContentEditable) {
                this.inputElement.textContent = newText;
                // Restaurar foco y cursor al final de la mención
                const newCursorPos = startIndex + selectedMention.length + 2; 
                this.setCaretPosition(this.inputElement, newCursorPos);
            } else {
                this.inputElement.value = newText;
                this.inputElement.selectionStart = this.inputElement.selectionEnd = startIndex + selectedMention.length + 2;
                this.inputElement.focus();
            }
        }
    }

    /**
     * Helper para mover el cursor en contenteditable
     */
    setCaretPosition(el, pos) {
        const range = document.createRange();
        const sel = window.getSelection();
        const child = el.firstChild || el; // Manejar caso vacío
        
        try {
            if (child.nodeType === 3) { // Text node
                const length = child.length;
                range.setStart(child, Math.min(pos, length));
            } else {
                range.setStart(el, 0);
            }
            range.collapse(true);
            sel.removeAllRanges();
            sel.addRange(range);
            el.focus();
        } catch (e) {
            console.warn("Error setting caret", e);
        }
    }

    // ============================================================
    // 2. STATIC METHODS (Para manejar clicks en menciones Wasm)
    // ============================================================

    static _mentionCallback = null;
    static _listenerInitialized = false;
    static _PREFIX = 'mention:';

    static registerHandler(callback) {
        this._mentionCallback = callback;
        this.ensureGlobalClickListener();
    }

    static ensureGlobalClickListener() {
        if (this._listenerInitialized) return;

        document.addEventListener('click', (event) => {
            const target = event.target.closest('[data-callback]');
            if (!target) return;

            const actionKey = target.getAttribute('data-callback');

            if (actionKey && actionKey.startsWith(MentionModule._PREFIX)) {
                if (typeof MentionModule._mentionCallback === 'function') {
                    event.preventDefault();
                    event.stopPropagation();
                    const username = actionKey.slice(MentionModule._PREFIX.length);
                    GuardModule.protect(() => MentionModule._mentionCallback(username));
                }
            }
        });

        this._listenerInitialized = true;
    }
}

export default MentionModule;